<template>
  <div class="fiat-detail-content">
    <DetailOrderHero :eyebrow="t('fiatDepositDetail.orderEyebrow')" :order-no="detail.order_no" :status="statusLabel" :status-type="statusType" :status-effect="detail.status===0?'pending':undefined">
      <div class="fiat-summary"><span class="fiat-summary__icon"><el-icon><Wallet /></el-icon></span><div><small>{{t('fiatDepositDetail.declaredAmount')}}</small><p><strong>{{formatMoney(detail.amount)}}</strong><span>{{detail.currency.code}}</span></p><em>{{detail.currency.name}}</em></div></div>
      <template #meta><div class="meta"><small>{{t('fiatDepositDetail.applicant')}}</small><strong>{{detail.user.company_name}}</strong><span>{{detail.user.email}}</span></div><div class="meta"><small>{{t('fiatDepositDetail.submittedAt')}}</small><strong>{{detail.submitted_at||'—'}}</strong></div></template>
    </DetailOrderHero>
    <div class="fiat-detail-content__workspace">
      <div class="fiat-detail-content__main">
        <DetailCard :title="t('fiatDepositDetail.remittanceInfo')" :description="t('fiatDepositDetail.remittanceInfoDesc')" icon="ri-bank-line"><DetailFieldGrid :items="remittanceItems" /></DetailCard>
        <DetailCard v-if="detail.files.length" :title="t('fiatDepositDetail.proofFiles')" :description="t('fiatDepositDetail.proofFilesDesc')" icon="ri-attachment-2"><ul class="proof-files"><li v-for="file in detail.files" :key="file.file_id"><span class="proof-files__type">{{file.extension?.toUpperCase()||'FILE'}}</span><div><strong>{{file.original_name}}</strong><small>{{formatSize(file.size)}} · {{file.uploaded_at}}</small></div><span class="proof-files__actions"><el-button plain size="small" :icon="View" @click="emit('preview',file.file_id)">{{t('fiatDepositDetail.preview')}}</el-button><el-button plain size="small" :icon="Download" @click="emit('download',file.file_id,file.original_name)">{{t('fiatDepositDetail.download')}}</el-button></span></li></ul></DetailCard>
        <DetailCard :title="t('fiatDepositDetail.reviewResult')" :description="t('fiatDepositDetail.reviewResultDesc')" icon="ri-shield-check-line"><DetailFieldGrid v-if="reviewItems.length" :items="reviewItems" /><p v-else class="empty-result">{{t('fiatDepositDetail.reviewPending')}}</p></DetailCard>
      </div>
      <DetailCard v-if="timelineItems.length" :title="t('fiatDepositDetail.timeline')" :description="t('fiatDepositDetail.timelineDesc')" icon="ri-time-line"><DetailTimeline :items="timelineItems" /></DetailCard>
    </div>
  </div>
</template>
<script setup lang="ts">
import { computed } from 'vue';import{Download,View,Wallet}from'@element-plus/icons-vue';import{useI18n}from'vue-i18n';import type{FiatOrderDetail}from'@/api/modules/fiatDeposit';import DetailCard from'@/components/detail/DetailCard.vue';import DetailFieldGrid,{type DetailFieldItem}from'@/components/detail/DetailFieldGrid.vue';import DetailOrderHero from'@/components/detail/DetailOrderHero.vue';import DetailTimeline from'@/components/detail/DetailTimeline.vue';import type{StatusBadgeType}from'@/components/admin/StatusBadge.vue';import{formatMoney}from'@/utils/formatMoney';
const props=defineProps<{detail:FiatOrderDetail}>();const emit=defineEmits<{(event:'preview',id:number):void;(event:'download',id:number,name:string):void}>();const{t}=useI18n();
const statusType=computed<StatusBadgeType>(()=>props.detail.status===1?'success':props.detail.status===2?'danger':'warning');const statusLabel=computed(()=>t(props.detail.status===1?'fiatDepositDetail.completed':props.detail.status===2?'fiatDepositDetail.rejected':'fiatDepositDetail.pending'));
const remittanceItems=computed<DetailFieldItem[]>(()=>[{label:t('fiatDepositDetail.payer'),value:props.detail.payer_name||'—'},{label:t('fiatDepositDetail.payerBank'),value:props.detail.payer_bank||'—'},{label:t('fiatDepositDetail.accountLast4'),value:props.detail.payer_account_last4||'—',mono:true},{label:t('fiatDepositDetail.reference'),value:props.detail.remittance_reference||'—',mono:true},{label:t('fiatDepositDetail.remittanceDate'),value:props.detail.remittance_date||'—'},{label:t('fiatDepositDetail.updatedAt'),value:props.detail.updated_at||'—'},{label:t('fiatDepositDetail.remark'),value:props.detail.remark||'—',wide:true}]);
const reviewItems=computed<DetailFieldItem[]>(()=>{const d=props.detail;if(d.status===0)return[];return[d.review.credited_at?{label:t('fiatDepositDetail.creditedAt'),value:d.review.credited_at,accent:true}:null,d.review.admin_name?{label:t('fiatDepositDetail.reviewer'),value:d.review.admin_name}:null,d.review.reviewed_at?{label:t('fiatDepositDetail.reviewedAt'),value:d.review.reviewed_at}:null,d.review.note?{label:t(d.status===2?'fiatDepositDetail.rejectionReason':'fiatDepositDetail.reviewNote'),value:d.review.note,wide:true}:null].filter(Boolean)as DetailFieldItem[];});
const timelineItems=computed(()=>props.detail.timeline.map(item=>({...item,name:['submitted','completed','rejected'].includes(item.event)?t(`fiatDepositDetail.timelineEvents.${item.event}`):item.name})));
function formatSize(size:number){if(size<1024)return`${size} B`;if(size<1024*1024)return`${(size/1024).toFixed(1)} KB`;return`${(size/1024/1024).toFixed(1)} MB`;}
</script>
<style scoped lang="scss">
.fiat-detail-content{display:grid;min-width:0;gap:18px}.fiat-detail-content__workspace{display:grid;min-width:0;align-items:start;grid-template-columns:minmax(0,1.5fr) minmax(320px,.8fr);gap:18px}.fiat-detail-content__main{display:grid;min-width:0;gap:18px}.fiat-summary{display:flex;align-items:center;gap:18px}.fiat-summary__icon{display:grid;width:58px;height:58px;flex:0 0 58px;place-items:center;border-radius:17px;color:#fff;background:linear-gradient(135deg,#19b8a8,#268ee6);font-size:28px}.fiat-summary small,.meta small{color:#74869b;font-size:12px}.fiat-summary p{display:flex;align-items:baseline;gap:9px;margin:6px 0 4px}.fiat-summary strong{color:#10243d;font-size:clamp(28px,3vw,40px)}.fiat-summary p span{color:#078f89;font-weight:700}.fiat-summary em{color:#74869b;font-size:13px;font-style:normal}.meta{display:grid;min-width:0;gap:3px}.meta small,.meta span{color:#74869b;font-size:11px;overflow-wrap:anywhere}.meta strong{color:#30475f;font-size:13px}.proof-files{display:grid;margin:0;padding:0;gap:8px;list-style:none}.proof-files li{display:grid;min-width:0;grid-template-columns:44px minmax(0,1fr) auto;align-items:center;gap:12px;padding:11px 12px;border:1px solid #e0e9f0;border-radius:10px;background:#f9fbfd}.proof-files__type{display:grid;height:36px;place-items:center;border-radius:9px;color:#126df0;background:#e9f2ff;font-size:9px;font-weight:750}.proof-files li>div{min-width:0}.proof-files strong{display:block;overflow:hidden;color:#203249;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.proof-files small{display:block;margin-top:4px;color:#718298;font-size:11px}.proof-files__actions{display:flex;gap:7px}.proof-files__actions :deep(.el-button + .el-button){margin-left:0}.empty-result{margin:0;padding:20px 0;color:#7b8b9f;font-size:13px}@include narrow{.fiat-detail-content__workspace{grid-template-columns:1fr}}@include mobile{.fiat-detail-content,.fiat-detail-content__workspace,.fiat-detail-content__main{gap:14px}.fiat-detail-content__workspace{grid-template-columns:1fr}.fiat-summary{align-items:flex-start;gap:12px}.fiat-summary__icon{width:48px;height:48px;flex-basis:48px;border-radius:14px;font-size:23px}.fiat-summary p{flex-wrap:wrap;gap:5px 8px}.fiat-summary strong{font-size:28px;overflow-wrap:anywhere}.proof-files li{grid-template-columns:40px minmax(0,1fr)}.proof-files__actions{grid-column:1/-1;justify-content:flex-end}}
</style>
